Prefix: '&8&l[&6Apia Lucky Clover&8&l] &7&l»'
CLOVER:
  MATERIAL: DOUBLE_PLANT
  NAME: '&eFour-Leaf Clover'
  LORE:
   - '&7Right Click and Earn Reward'
   - ''
   - '&aPrizes:'
   - '&8&l»» &c1 &bDiamond &7(%&650&7)'
   - '&8&l»» &c2 &bDiamonds &7(%&650&7)'
  CHANCE: 5

INVENTORY_FULL: '&7Your inventory is full, <AMOUNT> clover dropped to the ground.'
GIVE_YOUR_CLOVER: '&7You found a Four-Leaf Clover in grass'
SOUND: NOTE_PLING
REWARDS:
  - give <PLAYER> diamond 1
  - give <PLAYER> diamond 2
APIAJACKPOT_REWARD:
  ENABLED: true
  MONEY: 100000
  CHANCE: 10
APIAENVOY_REWARD: 
  ENABLED: true
  CHANCE: 10
SUCCESSFUL_MESSAGE: '&7Your rewards was given.'
RELOAD_MESSAGE: '&7ApiaLuckyClover reloaded.'
PERM_ERROR: '&7You do not have permission for this command'
GAVE_CLOVER: '&7You gave &e<AMOUNT> &7Four-Leaf Clover to &e<PLAYER>'
PLAYER_ERROR: '&7Player <PLAYER> is invalid'
HELP:
  - '&8&l»» &6/alc reload'
  - '&8&l»» &6/alc give <player> <amount>'
UPDATE: true