name: ApiaLuckyClover
main: me.bertek41.alc.ALC
version: maven.version
description: Lucky Clover Plugin
authors: [oSoloTurk, bertek41]
website: 'https://mcdeyiz.com/'
api-version: 1.13
depend: [Vault]
commands:
  alc:
    description: Main Command of Apia Lucky Clover Plugin
    aliases: [apialuckyclover]
    permission: [alc.reload, alc.give]