name: ApiaLuckyClover
main: me.bertek41.alc.ALC
version: maven.version
description: Lucky Clover Plugin
authors: [oSoloTurk, bertek41]
website: 'https://mcdeyiz.com/'
api-version: 1.13
commands:
  alc:
    description: Main command
    aliases: [apialuckyclover, clover]
    permission: alc.reload