Prefix: Apia Lucky Clover
CLOVER:
  MATERIAL: DOUBLE_PLANT
  NAME: '&eLucky Clover'
  LORE: '&7RightClick for Use'
  CHANCE: 5

INVENTORY_FULL: '&7Your Inventory is Fully, Clover Drop at here'
GIVE_YOUR_CLOVER: '&7You find a lucky clover in grass'
SOUND: NOTE_PLING
REWARDS:
  - broadcast <PLAYER> use a CLOVER
SUCCESFULL-MESSAGE: '&7Gived Your Rewards'